language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: 
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,sympy numpy scipy sympy
  - python setup.py install
script: py.test
