language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - python setup.py develop
script:
  - py.test --cov=bayesloop
after_success:
  - coveralls
