language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,sympy numpy scipy==0.19.1 sympy==1.1
  - python setup.py develop
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - py.test --cov=bayesloop
after_success:
  - coveralls
